### ISSUE TITLE
Boost icon misalignment when clicked

### ISSUE THREAD

**Issue by cadusilva** [ronilaukkarinen/mastodon-bird-ui#112]
The boost icon loses alignment when clicked. This happens when you open a toot in the advanced interface. Once you click the icon, the bug happens.

![chrome_2024-02-27_16-05-28](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/8684263/365f9ae2-35b0-48c3-bd34-e6464ecc00b8)

I couldn't reproduce the problem with one column, when opening the toot permalink in another tab. Also doesn't happen when the toot is not opened, just showing in one of the columns in the advanced interface.

As seen in the image above, it realigns itself when you click elsewhere.

Bird UI version: `2.0.0rc18`

**Comment by cadusilva** [comment]
Tested with Firefox `124.0b4 (64-bit)` and Chromium `122.0.6261.56`.

**Comment by ronilaukkarinen** [comment]
Thanks. There might be something wrong with the alignment of the animation. This is implemented a bit trickily with scale and absolute positioning of the animated image. I'd much prefer using direct SVG animation instead of a hacky png in base64, but I have no skill and time for animating SVGs like that, at least not yet. Would be amazing to get this re-done as SVG:

![image](https://private-user-images.githubusercontent.com/1534150/270117346-ef02d2b8-14bc-4dbc-9b48-112c723c71cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNjMwOTIsIm5iZiI6MTcwOTA2Mjc5MiwicGF0aCI6Ii8xNTM0MTUwLzI3MDExNzM0Ni1lZjAyZDJiOC0xNGJjLTRkYmMtOWI0OC0xMTJjNzIzYzcxY2IuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMTkzOTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2JhZDYwNjEyZjM5YzJhNTc3MzY0MTIyNDgzM2JlNGIyZGVhZGVjYzFjYjQ2ODkwZGRkZGEwNDMwYWZiZDNkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LvTAugnu2Lu9re288saQnSzSteXyU7bVEebIJcpp548)

**Comment by 0ranki** [comment]
On mobile Chromium, there's some related action happening after clicking the star icon (number is offset to the right).
![Screenshot_20240327-133434](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/50285623/909eff43-53cb-41a2-a7bf-8e34b5257046)

The heart icons work like they should.

Thought it's better to mention here than open a separate issue.

**Comment by ronilaukkarinen** [comment]
> Thought it's better to mention here than open a separate issue.

That is actually similar but a completely separate issue. This issue is about the boost icons.

The markup for these animated icons is a bit cumbersome because you can't actually modify a lot with the SVG icon that comes from core, so you need to play with the remaining focus pseudo and classes that you have. When the element is absolute positioned the number kinda stretches the area.

Like I explained above, it's tricky to fix for all scenarios, but I'll try when I have time.
