### ISSUE TITLE
Suggested Re-branding for Future  Not Using "Bird" or Twitter in the Name

### ISSUE THREAD

**Issue by Timothyjchambers** [ronilaukkarinen/mastodon-bird-ui#30]
I was just judging from my trial of using this at Indieweb.social I think if the theme simply didn't use the word "Bird" UI  it would have avoided some adverse reaction from a minority of our users evaluating it.  I think it is fine to include the inspiration to some of the elements that Twitter's UI UX got right that inspired it in the notes, but maybe just consider a new brand for it going forward. 

I noticed when Stux added it to his server, they renamed it "Elephant" to I think avoid that same issue.

**Comment by ronilaukkarinen** [comment]
Hah, I understand the notion as I already "rebranded" it from Mastodon Twitter UI to Mastodon Bird UI. I started this project for fun so that the first version was exactly like Twitter, with even Twitter colors. The UI still mimics pretty much Twitter so it is kinda 90% the source of origin.

I personally like Twitter UI and in my mind there should be some reference. There will always be those who think the looks alone are "too Twitter". 

Other reason why I'm a bit hesitant to changing it now is that people are use to the name and hashtags #BirdUI and #MastodonBirdUI are widely in use in discussion and changes. 

Everyone can freely name it as they want, it's not official and it's open source. The theme was not originally meant as an option so that the name was visible but as a replacement for small instance owners.

A bird doesn't have always mean Twitter.
