### ISSUE TITLE
Reply lines become misleading

### ISSUE THREAD

**Issue by Freeplayg** [ronilaukkarinen/mastodon-bird-ui#4]
The lines are usually supposed to show that a reply is a direct reply to the one above, however this reply below isn't responding to the one above it, it's replying to another post above the rest.
![image](https://user-images.githubusercontent.com/40742947/227785933-dbe33b39-006f-4940-90e7-3a6ef6f533d0.png)

Although it does look more like Twitter, I feel it's probably best to remove them for now because Mastodon's way of handling replies don't work for it

**Comment by ronilaukkarinen** [comment]
Yes, it's intentional.

> Although it does look more like Twitter, I feel it's probably best to remove them for now because Mastodon's way of handling replies don't work for it

Yeah it's made to look like Twitter, but the lines have no actual relation to the actual replies because there's no helpers for that (Mastodon doesn't support threading at the moment).

They just feel so "empty" without any indication or relation to each other:

![Screen-Shot-2023-03-27-15-50-32 94](https://user-images.githubusercontent.com/1534150/227944813-8ba5a047-e0f5-44ce-8032-47d1d6967302.png)

I understand it's the same way than in the default UI like this, but I still kinda like it has "something".

I'm not going to instantly remove the reply lines, but will think about it. I'm open to ideas here. Faded or dashed line or something? 🤔

**Comment by ronilaukkarinen** [comment]
Yes, it's intentional.

> Although it does look more like Twitter, I feel it's probably best to remove them for now because Mastodon's way of handling replies don't work for it

Yeah it's made to look like Twitter, but the lines have no actual relation to the actual replies because there's no helpers for that (Mastodon doesn't support threading at the moment).

They just feel so "empty" without any indication or relation to each other:

![Screen-Shot-2023-03-27-15-50-32 94](https://user-images.githubusercontent.com/1534150/227944813-8ba5a047-e0f5-44ce-8032-47d1d6967302.png)

I understand it's the same way than in the default UI like this, but I still kinda like it has "something".

I'm not going to instantly remove the reply lines, but will think about it. I'm open to ideas here. Faded or dashed line or something? 🤔

**Comment by jarilehtinen** [comment]
Horizontal lines between the posts? Vertical lines indeed create an illusion of related posts.

**Comment by ronilaukkarinen** [comment]
The current structure allows only for them all to be linked or none of them. In my opinion neither is good. Some day I'd like it to be like this:

![Screenshot_20230402-002137_Chrome-01](https://user-images.githubusercontent.com/1534150/229314424-0d80d0db-b070-4afc-b9c7-0638a30dbc6d.jpeg)

I'll try to get helper classes modified to my instance first and then make a styles for them. After this I'll revert the default to non-lined version. I hope Mastodon core will have some helper classes in the DOM in the future. Right now they are all on the same level.

**Comment by ronilaukkarinen** [comment]
Just implemented a Mastodon back end code to get helper divs and classes and achieved this:

![image](https://user-images.githubusercontent.com/1534150/229343534-8d15bf07-2e99-4f97-9d58-a51480e01016.png)

If there is no such classes, we just show borders without any lines:

![image](https://user-images.githubusercontent.com/1534150/229343561-1b845b80-ff7e-4990-a95d-d867328cf745.png)

Going to push it to next rc version.

**Comment by ronilaukkarinen** [comment]
Changed the structure to be more reliable, see [commit](https://github.com/ronilaukkarinen/mastodon-bird-ui/commit/23c0912dc98bd8b237b2fe9b1bbf1712aa42ad5d).
