### ISSUE TITLE
android: toolbar doesn't move with firefox addressbar

### ISSUE THREAD

**Issue by ikke-t** [ronilaukkarinen/mastodon-bird-ui#50]
Hi,

See screenshot how android firefox dynamic addressbar disappearing leaves birdui toolbar element hanging:

![Screenshot_2023-07-10-18-30-43-15_984e1414ae90666a90f12ff17ec14a7f](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1146409/12216691-9c59-46b2-b6d4-2459227b2b26)

While fixing it, why not autohide birdUI toolbar as well 🙏

I can look after a similar issue I made for Elk, which got fixed.

This is related to another issue. Sometimes the button touch is miscalculated by the same amount when FF toolbar moves.

So the page should take into account if ff toolbar is visible or not. Now it fails noticing the change.

**Comment by ikke-t** [comment]
See elk issue here https://github.com/elk-zone/elk/issues/1558

**Comment by ronilaukkarinen** [comment]
This is not really Mastodon Bird UI issue, because that code has nothing to do with Mastodon Bird UI :sweat_smile: It is related to [my fork of Mastodon](https://github.com/ronilaukkarinen/mastodon/tree/mementomori-social-mods-4.1.4-nightly-20230707) and never was implemented with Mastodon Bird UI, only on [mementomori.social as a feature](https://help.mementomori.social/mementomori.social/instance-features#top-bar-scrolls-out-of-the-way).

However, I tested it on Firefox and didn't spot any issues :thinking: 

I suggest using a Chrome app for Mastodon for now or if it bugs too much I can perhaps disable the feature, but I have no idea how to solve it otherwise.

Firefox on Android 13 (Google Pixel/OPO 8T):

![ezgif com-optimize (1)](https://github.com/ronilaukkarinen/mastodon-bird-ui/assets/1534150/6133c843-70a5-4d3d-ba1c-729ac434ecd1)

**Comment by ikke-t** [comment]
Yes, it doesn't always happen. I wonder why is that. Sometimes this and elk both gets confused, like missing some resize event. Then it stays. Also latest android on 1+ here.
